apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-master-buildtools
  namespace: devops
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: standard-retain
