apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkinshome-pvc
  namespace: devops
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 200G
  storageClassName: standard
  volumeMode: Filesystem
