apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-slave01-workdir
  namespace: devops
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: standard-retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-buildtools
  namespace: devops
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: standard-retain
