---
kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    app: slave01
  name: slave01
  namespace: devops
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: slave01
  template:
    metadata:
      labels:
        app: slave01
      namespace: devops
      name: slave01
    spec:
      containers:
        - name: slave01
          image: jenkins/jnlp-slave:4.13.2-1-jdk11
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: 1000m
              memory: 2Gi
            requests:
              cpu: 500m
              memory: 512Mi
          volumeMounts:
            - name: slave01-workdir
              mountPath: /home/jenkins/workspace
            - name: buildtools
              mountPath: /home/jenkins/buildtools
          env:
            - name: JENKINS_URL
              value: http://10.44.24.216:8080
            - name: JENKINS_SECRET
              value: c60d82ef0a75dd20580790d657efa3536c6923131ac64a53b476205bdeb49462
            - name: JENKINS_AGENT_NAME
              value: slave01
            - name: JENKINS_AGENT_WORKDIR
              value: /home/jenkins/workspace
      securityContext:
        fsGroup: 1000

      volumes:
        - name: slave01-workdir
          persistentVolumeClaim:
            claimName: jenkins-slave01-workdir
        - name: buildtools
          persistentVolumeClaim:
            claimName: jenkins-buildtools
